
all:
  hosts:
    web1:
      ansible_host: web1
      ansible_user: root
      ansible_password: Passw0rd
      ansible_become: yes
    web2:
      ansible_host: web2
      ansible_user: root
      ansible_password: Passw0rd
      ansible_become: yes
  children:
    web_servers:
      hosts:
        web1:
        web2:
